"""The analysis behind paper 1 (P11, E17): read the collapse-code runs (one JSON per run, as written by
experiments/bench/E17_collapse_code/run_collapse_code.py), apply the pre-registered analysis, and write the results
table and the figures. Simulator rehearsals and hardware runs go through exactly the same code, so replacing the
rehearsal data with hardware data regenerates the paper's results.

    python -m qll.analysis.collapse_report research/papers/P1_collapse_code/data/rehearsal --out research/papers/P1_collapse_code

Analysis (fixed before data; see systems/program/08_first_paper.md)
--------------------------------------------------------------------
For each run: the likelihood-ratio test of independence of Bob's outcome and Alice's bit, at a family-wise level of
1 % with a Bonferroni correction over the runs that are not controls [casella2002]; Clopper-Pearson intervals on
Bob's conditional rates [clopper1934]; and the 99 % upper bound on the information per use from the convexity of
mutual information in the channel [cover2006] (qll/circuits/collapse_signalling.py). Runs with an injected leak are
controls: they must be detected. The bias of every run is then set against the coupling distance of its qubit pair.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np

from qll.circuits import collapse_signalling as C

BLUE, ORANGE, AQUA, MUTED, GRID, CRITICAL, GOOD = "#2a78d6", "#eb6834", "#1baf7a", "#8a887f", "#e6e5df", "#d03b3b", "#0ca30c"


def load(folder: Path) -> list[dict]:
    runs = []
    for f in sorted(Path(folder).glob("*.json")):
        rec = json.loads(f.read_text(encoding="utf-8"))
        if rec.get("experiment", "").startswith("E17"):
            rec["_file"] = f.name
            runs.append(rec)
    if not runs:
        raise ValueError(f"no E17 runs in {folder}")
    return runs


def analyze_runs(runs: list[dict], family_level: float = 0.99) -> list[dict]:
    tests = [r for r in runs if not r.get("leak_injected")]
    per_test_alpha = (1 - family_level) / max(len(tests), 1)
    rows = []
    for r in runs:
        x, b = C.counts_to_outcomes({int(k): v for k, v in r["counts"].items()})
        v = C.analyze(x, b, level=family_level)
        control = bool(r.get("leak_injected"))
        detected = v.p_value < per_test_alpha
        rows.append({"file": r["_file"], "backend": r["backend"], "scheme": r["scheme"], "pair": tuple(r["layout"]),
                     "distance": r.get("coupling_distance"), "control": control, "leak": r.get("leak_injected", 0.0),
                     "uses_per_value": int(v.table.sum() // 2), "p1": v.p1_given_x, "bias": v.bias,
                     "bias_interval": v.bias_interval, "p_value": v.p_value, "mi_upper": v.mi_upper,
                     "detected": detected, "as_expected": detected if control else not detected})
    return rows


def results_md(rows: list[dict], title: str = "Results") -> str:
    tests = [r for r in rows if not r["control"]]
    out = [f"# {title}", "",
           "*Generated by `python -m qll.analysis.collapse_report`; edit the data, not this file.*", "",
           f"{len(tests)} test runs at a family-wise level of 1 % (Bonferroni: each run at {0.01 / max(len(tests), 1):.2g}), "
           f"{len(rows) - len(tests)} control runs with an injected leak. Methods: the likelihood-ratio test of "
           "independence (Casella and Berger (2002)), Clopper and Pearson (1934) intervals on Bob's rates, and the "
           "corner bound on mutual information from its convexity in the channel (Cover and Thomas (2006)).", "",
           "| Run | Backend | Scheme | Qubit pair (couplers apart) | Uses per value | P(b=1 given x=0) | P(b=1 given x=1) | Bias (99 % interval) | p-value | Information per use, 99 % upper bound | Verdict |",
           "|---|---|---|---|---|---|---|---|---|---|---|"]
    for i, r in enumerate(rows, 1):
        pair = f"{r['pair'][0]}–{r['pair'][1]}" + (f" ({r['distance']})" if r["distance"] is not None else "")
        kind = f"control, leak {r['leak']:g}" if r["control"] else r["scheme"]
        verdict = ("detected, as it must be" if r["detected"] else "MISSED: check the analysis") if r["control"] else \
                  ("dependence: check crosstalk (E16)" if r["detected"] else "no dependence")
        out.append(f"| {i} | {r['backend']} | {kind} | {pair} | {r['uses_per_value']:,} | {r['p1'][0]:.4f} | {r['p1'][1]:.4f} | "
                   f"{r['bias']:+.4f} ({r['bias_interval'][0]:+.4f}, {r['bias_interval'][1]:+.4f}) | {r['p_value']:.3g} | {r['mi_upper']:.1e} bit | {verdict} |")
    if tests:
        best = min(r["mi_upper"] for r in tests)
        out += ["", f"Tightest bound: {best:.1e} bit per use. Every test run as expected: {all(r['as_expected'] for r in tests)}. "
                    f"Every control detected: {all(r['detected'] for r in rows if r['control'])}.", ""]
    return "\n".join(out)


def figures(rows: list[dict], out: Path) -> list[Path]:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    out.mkdir(parents=True, exist_ok=True)
    paths = []

    def save(fig, name):
        fig.tight_layout()
        p = out / f"{name}.svg"
        with matplotlib.rc_context({"svg.hashsalt": name}):
            fig.savefig(p, metadata={"Date": None})
        plt.close(fig)
        paths.append(p)

    # 1. Bob's conditional rates per run, with 99 % intervals
    fig, ax = plt.subplots(figsize=(8.8, 0.42 * len(rows) + 1.4))
    for i, r in enumerate(rows[::-1]):
        n = r["uses_per_value"]
        for k, (col, mk) in enumerate(((BLUE, "o"), (ORANGE, "s"))):
            p = r["p1"][k]
            lo, hi = C.clopper_pearson(int(round(p * n)), n, 0.01)
            ax.errorbar(p, i + (0.12 if k else -0.12), xerr=[[p - lo], [hi - p]], fmt=mk, color=col, ms=5, capsize=2,
                        label=(f"Alice's bit x = {k}" if i == 0 else None))
    labels = [f"{r['backend']} · {('leak ' + format(r['leak'], 'g')) if r['control'] else r['scheme']} · {r['pair'][0]}–{r['pair'][1]}" for r in rows[::-1]]
    ax.set_yticks(range(len(rows)), labels, fontsize=7)
    ax.axvline(0.5, color=MUTED, lw=1, ls="--")
    ax.set_xlabel("P(Bob reads 1)")
    ax.set_title("Bob's outcomes alone, for each of Alice's choices (99 % intervals)", loc="left", fontsize=10)
    ax.legend(frameon=False, fontsize=8, loc="lower left")
    ax.grid(axis="x", color=GRID); ax.set_axisbelow(True)
    for s in ("top", "right"):
        ax.spines[s].set_visible(False)
    save(fig, "rates")

    # 2. the bound on information per use against the number of uses, with the expected 1/n curve
    fig, ax = plt.subplots(figsize=(6.4, 4.0))
    ns = np.logspace(3, 7, 9).astype(int)
    exp_ub = []
    for n in ns:                                     # the bound a run of n uses per value gets when Bob's rates are exactly 1/2
        k = n // 2
        lo, hi = C.clopper_pearson(k, n, 0.005)
        exp_ub.append(max(C.mutual_information(a, b) for a in (lo, hi) for b in (lo, hi)))
    ax.loglog(ns, exp_ub, color=MUTED, lw=2, label="expected bound with no dependence")
    t = [r for r in rows if not r["control"]]
    ax.loglog([r["uses_per_value"] for r in t], [r["mi_upper"] for r in t], "o", color=BLUE, mec="white", ms=7, label="runs")
    ax.set_xlabel("uses per message value"); ax.set_ylabel("information per use, 99 % upper bound (bit)")
    ax.set_title("A null result is a bound that shrinks as 1/n", loc="left", fontsize=10)
    ax.legend(frameon=False, fontsize=8); ax.grid(True, which="both", color=GRID, lw=0.6); ax.set_axisbelow(True)
    for s in ("top", "right"):
        ax.spines[s].set_visible(False)
    save(fig, "bound_vs_uses")

    # 3. bias against qubit separation (hardware or fake devices only)
    d = [r for r in t if r["distance"] is not None]
    if d:
        fig, ax = plt.subplots(figsize=(6.4, 4.0))
        markers = {"basis": "o", "measure": "s", "flip": "^"}
        for sch, mk in markers.items():
            rr = [r for r in d if r["scheme"] == sch]
            if rr:
                ax.errorbar([r["distance"] + {"basis": -0.1, "measure": 0, "flip": 0.1}[sch] for r in rr], [r["bias"] for r in rr],
                            yerr=[[r["bias"] - r["bias_interval"][0] for r in rr], [r["bias_interval"][1] - r["bias"] for r in rr]],
                            fmt=mk, color={"basis": BLUE, "measure": ORANGE, "flip": AQUA}[sch], capsize=2, ms=6, label=sch)
        ax.axhline(0, color=MUTED, lw=1)
        ax.set_xlabel("couplers between Alice's and Bob's qubits"); ax.set_ylabel("bias in Bob's outcome rate")
        ax.set_title("Any dependence should fall with distance if it is crosstalk", loc="left", fontsize=10)
        ax.legend(frameon=False, fontsize=8); ax.grid(True, color=GRID); ax.set_axisbelow(True)
        for s in ("top", "right"):
            ax.spines[s].set_visible(False)
        save(fig, "bias_vs_distance")
    return paths


def main(argv=None) -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("data"); ap.add_argument("--out", required=True); ap.add_argument("--title", default="Results")
    a = ap.parse_args(argv)
    rows = analyze_runs(load(Path(a.data)))
    out = Path(a.out)
    (out / "results.md").write_text(results_md(rows, a.title), encoding="utf-8")
    figs = figures(rows, out / "figures")
    print(f"wrote {out / 'results.md'} and {len(figs)} figures from {len(rows)} runs")


if __name__ == "__main__":
    main()
