"""Build docs/references.md, a browsable index of every BibTeX entry in docs/*.bib, grouped by topic.
Run after editing any .bib file: python scripts/build_reference_index.py"""
from __future__ import annotations

import re
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"
TOPIC_RULES = [  # (regex on title+key, topic)
    (r"teleport|swapping|dense coding|bell-state|Bell state", "Teleportation and entanglement swapping"),
    (r"Bell|nonlocal|EPR|Einstein|hidden variable|CHSH|local realism|loophole", "Bell tests and nonlocality"),
    (r"key distribution|QKD|cryptograph|decoy|BB84|twin-field|device-independent|secret key|privacy amplification|reconciliation|hack", "Quantum key distribution"),
    (r"repeater|memory|memories|coherence time|storage|ensemble|purification|distillation", "Repeaters and memories"),
    (r"satellite|space|Micius|deep space|orbit|free-space|free space|daylight|constellation", "Satellite and space links"),
    (r"nitrogen|NV|diamond|vacancy|colour centre|color center|silicon-vacancy|SiV", "Diamond color centers"),
    (r"superconduct|transmon|Josephson|circuit QED|Cooper|fluxonium|cavity|GKP|grid states|oscillator", "Superconducting and bosonic qubits"),
    (r"spin qubit|quantum dot|silicon|donor", "Spin qubits"),
    (r"ion|Mølmer|Cirac|trapped", "Trapped ions"),
    (r"Rydberg|atom array|neutral atom|tweezer|reconfigurable atom", "Neutral atoms"),
    (r"photon|linear optic|down-conversion|down conversion|parametric|beam splitter|interference|single-photon|detector|SPDC|squeez", "Photonics and detectors"),
    (r"Majorana|topological|anyon|Kitaev", "Topological"),
    (r"error correc|surface code|stabilizer|fault|threshold|decoherence|dynamical decoupling|noise|damping|Lindblad|benchmark", "Error correction, noise, and benchmarking"),
    (r"algorithm|factor|search|Grover|Shor|complexity|simulat|chemistry|variational", "Algorithms, complexity, and simulation"),
    (r"transduc|conversion|frequency conversion", "Transduction and frequency conversion"),
    (r"random|entropy source|QRNG", "Randomness"),
    (r"Qiskit|Stim|QuTiP|SeQUeNCe|NetSquid|QuNetSim|Perceval|software|simulator", "Software"),
    (r"CODATA|SI|astronomical unit|IAU|Systems Engineering|FIPS|SP 800|standard", "Constants and standards"),
    (r"teaching|undergraduate|low-cost|3D printed|outreach|open-source|Uncut Gem|magnetometer|sensing|metrology|clock", "Teaching labs, sensing, and clocks"),
]


def parse_bib(text: str):
    i = 0
    while True:
        m = re.search(r"@(\w+)\{([^,]+),", text[i:])
        if not m:
            return
        start = i + m.end()
        depth, j = 1, start
        while j < len(text) and depth:
            depth += {"{": 1, "}": -1}.get(text[j], 0)
            j += 1
        body, key = text[start:j - 1], m.group(2).strip()
        i = j
        fields = {}
        for fm in re.finditer(r"(\w+)\s*=\s*\{((?:[^{}]|\{(?:[^{}]|\{[^{}]*\})*\})*)\}", body):
            fields[fm.group(1).lower()] = re.sub(r"\s+", " ", fm.group(2)).replace("{", "").replace("}", "").strip()
        yield key, fields


def classify(key: str, f: dict) -> str:
    hay = f"{key} {f.get('title','')} {f.get('journal','')} {f.get('booktitle','')}"
    for rx, topic in TOPIC_RULES:
        if re.search(rx, hay, re.I):
            return topic
    return "Foundations and general"


def status(f: dict) -> str:
    note = f.get("note", "").lower()
    if "verified" in note and "todo" not in note:
        return "verified"
    if "todo" in note:
        return "TODO verify"
    return "confident" if f.get("doi") else "no DOI"


def main() -> None:
    groups = defaultdict(list)
    seen = set()
    for bib in sorted(DOCS.glob("references*.bib")):
        for key, f in parse_bib(bib.read_text(encoding="utf-8")):
            if key in seen:
                continue
            seen.add(key)
            groups[classify(key, f)].append((key, f, bib.name))
    out = ["# References", "", f"{len(seen)} entries from `docs/references*.bib`, grouped by topic and generated by `scripts/build_reference_index.py`. ",
           "**verified** = DOI checked against the publisher in this project; **confident** = well-known DOI, re-check before citing in code; **TODO verify** = do not cite from code yet.", ""]
    for topic in sorted(groups):
        rows = sorted(groups[topic], key=lambda r: (r[1].get("year", ""), r[0]))
        out += [f"## {topic}", "", "| Key | Reference | Status |", "|---|---|---|"]
        for key, f, src in rows:
            author = f.get("author", "?").split(" and ")[0].split(",")[0]
            etal = " et al." if " and " in f.get("author", "") else ""
            venue = f.get("journal") or f.get("booktitle") or f.get("publisher") or f.get("howpublished", "")
            vol = f", {f['volume']}" if f.get("volume") else ""
            pages = f", {f['pages']}" if f.get("pages") else ""
            doi = f.get("doi")
            arx = f.get("eprint")
            link = f" [doi](https://doi.org/{doi})" if doi else (f" [arXiv](https://arxiv.org/abs/{arx})" if arx else "")
            out.append(f"| `{key}` | {author}{etal} ({f.get('year','?')}). {f.get('title','?')}. *{venue}*{vol}{pages}.{link} | {status(f)} |")
        out.append("")
    (DOCS / "references.md").write_text("\n".join(out), encoding="utf-8")
    print(f"wrote docs/references.md with {len(seen)} entries in {len(groups)} topics")


if __name__ == "__main__":
    main()
